BEGIN {
    in_method = 0
}
/^    def set_birthday\(self, log_cb=None, account_data: Optional\[dict\] = None\) -> bool:/ {
    in_method = 1
    print "    def set_birthday(self, log_cb=None, account_data: Optional[dict] = None) -> bool:"
    print "        \"\"\""
    print "        Ultra-efficient, simplified birthday setter."
    print "        Swipes down forcefully on the year column and proceeds."
    print "        \"\"\""
    print "        if self.stop_requested:"
    print "            return False"
    print ""
    print "        def log(msg, level=\"info\"):"
    print "            if log_cb:"
    print "                try: log_cb(msg, level)"
    print "                except Exception: pass"
    print ""
    print "        w, h = self.get_screen_size()"
    print "        log(\"🎂 [Birthday] Setting adult age aggressively...\", \"info\")"
    print ""
    print "        # 1. Bring up the date picker if it isn't visible yet"
    print "        xml = self.dump_ui().lower()"
    print "        if \"numberpicker\" not in xml and \"datepicker\" not in xml and \"button1\" not in xml:"
    print "            log(\"👉 Opening Date Picker...\", \"info\")"
    print "            coords = self.find_text_coordinates([\"set date\", \"birthday\", \"january\", \"february\", \"march\", \"date of birth\", \"add your birthday\", \"year\"], max_y=int(h * 0.60))"
    print "            if coords: self._tap(coords[0], coords[1])"
    print "            else: self._tap(int(w * 0.50), int(h * 0.35))"
    print "            time.sleep(1.0)"
    print "        "
    print "        # 2. Forceful Swipes DOWN on the right side of the screen (where the Year wheel sits)"
    print "        log(\"🔄 Spinning the year wheel back...\", \"info\")"
    print "        year_x = int(w * 0.80)"
    print "        y_top = int(h * 0.40)"
    print "        y_bottom = int(h * 0.70)"
    print "        "
    print "        for _ in range(6):"
    print "            self._run_adb_args([\"shell\", \"input\", \"swipe\", str(year_x), str(y_top), str(year_x), str(y_bottom), \"100\"])"
    print "            time.sleep(0.2)"
    print "        "
    print "        self._tap(year_x, (y_top + y_bottom) // 2)"
    print "        time.sleep(0.5)"
    print ""
    print "        # 3. Confirm the date picker"
    print "        self.confirm_date_picker(log_cb=log)"
    print "        time.sleep(1.0)"
    print "        check_xml = self.dump_ui().lower()"
    print "        if \"button1\" in check_xml or \"numberpicker\" in check_xml:"
    print "            self.confirm_date_picker(log_cb=log)"
    print "            time.sleep(1.0)"
    print ""
    print "        # 4. Tap the 'Next' button on the main birthday screen"
    print "        log(\"👉 Tapping 'Next' to proceed...\", \"info\")"
    print "        next_coords = self.find_text_coordinates([\"Next\", \"Continue\", \"Далее\", \"Siguiente\"], min_y=int(h * 0.40))"
    print "        if next_coords:"
    print "            self._tap(next_coords[0], next_coords[1])"
    print "        else:"
    print "            self._tap(int(w * 0.50), int(h * 0.45))"
    print "            time.sleep(0.3)"
    print "            self._tap(int(w * 0.50), int(h * 0.52))"
    print ""
    print "        self._run_adb_args([\"shell\", \"input\", \"keyevent\", \"66\"])"
    print "        time.sleep(1.5)"
    print ""
    print "        # 5. Handle confirmations or errors"
    print "        post_xml = self.dump_ui().lower()"
    print "        if any(k in post_xml for k in [\"years old\", \"confirm your age\", \"confirm your birthday\", \"is this your\", \"how old are you\"]):"
    print "            log(\"🎂 Confirming age dialog...\", \"info\")"
    print "            self.tap_text([\"OK\", \"Ok\", \"Confirm\", \"Yes\", \"Continue\"], timeout=1.0)"
    print "            time.sleep(1.5)"
    print "            post_xml = self.dump_ui().lower()"
    print ""
    print "        if any(k in post_xml for k in [\"at least 13\", \"valid birthday\", \"can't continue\", \"sorry\"]):"
    print "            log(\"⚠️ Age error detected. Swiping again...\", \"warning\")"
    print "            self.tap_text([\"OK\", \"Ok\", \"Dismiss\", \"Close\", \"Cancel\"], timeout=1.0)"
    print "            time.sleep(0.5)"
    print "            for _ in range(8):"
    print "                self._run_adb_args([\"shell\", \"input\", \"swipe\", str(year_x), str(y_top), str(year_x), str(y_bottom), \"100\"])"
    print "            self._tap(year_x, (y_top + y_bottom) // 2)"
    print "            time.sleep(0.5)"
    print "            self.confirm_date_picker(log_cb=log)"
    print "            time.sleep(1.0)"
    print "            next_coords = self.find_text_coordinates([\"Next\", \"Continue\"], min_y=int(h * 0.40))"
    print "            if next_coords: self._tap(next_coords[0], next_coords[1])"
    print "            else: self._tap(int(w * 0.50), int(h * 0.45))"
    print "            self._run_adb_args([\"shell\", \"input\", \"keyevent\", \"66\"])"
    print "            time.sleep(1.5)"
    print "        "
    print "        return True"
    next
}
in_method == 1 && /^    def confirm_date_picker\(self, log_cb=None\) -> bool:/ {
    in_method = 0
    print $0
    next
}
in_method == 0 {
    print $0
}
